/**
 * 役の定数定義
 */

import type { YakuDefinition, YakuName } from '../types'

/**
 * すべての役の定義
 */
export const YAKU_DEFINITIONS: Record<YakuName, YakuDefinition> = {
  // 1翻役
  riichi: {
    name: 'riichi',
    displayName: '立直',
    han: 1,
    openHan: null, // 鳴けない
    category: 'situational',
    isYakuman: false,
    description: '門前で立直を宣言し和了する',
  },
  ippatsu: {
    name: 'ippatsu',
    displayName: '一発',
    han: 1,
    openHan: null,
    category: 'situational',
    isYakuman: false,
    description: '立直後、1巡以内に和了する',
  },
  tsumo: {
    name: 'tsumo',
    displayName: '門前清自摸和',
    han: 1,
    openHan: null,
    category: 'situational',
    isYakuman: false,
    description: '門前でツモ和了する',
  },
  tanyao: {
    name: 'tanyao',
    displayName: '断么九',
    han: 1,
    openHan: 1,
    category: 'hand',
    isYakuman: false,
    description: '么九牌を使わずに和了する',
  },
  pinfu: {
    name: 'pinfu',
    displayName: '平和',
    han: 1,
    openHan: null,
    category: 'hand',
    isYakuman: false,
    description: '門前・全順子・両面待ち・役牌でない雀頭',
  },
  iipeikou: {
    name: 'iipeikou',
    displayName: '一盃口',
    han: 1,
    openHan: null,
    category: 'hand',
    isYakuman: false,
    description: '同じ順子が2組ある',
  },
  'yakuhai-wind': {
    name: 'yakuhai-wind',
    displayName: '役牌（風牌）',
    han: 1,
    openHan: 1,
    category: 'hand',
    isYakuman: false,
    description: '自風または場風の刻子',
  },
  'yakuhai-dragon': {
    name: 'yakuhai-dragon',
    displayName: '役牌（三元牌）',
    han: 1,
    openHan: 1,
    category: 'hand',
    isYakuman: false,
    description: '三元牌の刻子',
  },
  haitei: {
    name: 'haitei',
    displayName: '海底撈月',
    han: 1,
    openHan: 1,
    category: 'situational',
    isYakuman: false,
    description: '海底牌でツモ和了する',
  },
  houtei: {
    name: 'houtei',
    displayName: '河底撈魚',
    han: 1,
    openHan: 1,
    category: 'situational',
    isYakuman: false,
    description: '最後の捨て牌でロン和了する',
  },
  rinshan: {
    name: 'rinshan',
    displayName: '嶺上開花',
    han: 1,
    openHan: 1,
    category: 'situational',
    isYakuman: false,
    description: '嶺上牌でツモ和了する',
  },
  chankan: {
    name: 'chankan',
    displayName: '槍槓',
    han: 1,
    openHan: 1,
    category: 'situational',
    isYakuman: false,
    description: '加槓された牌でロン和了する',
  },

  // 2翻役
  'double-riichi': {
    name: 'double-riichi',
    displayName: '両立直',
    han: 2,
    openHan: null,
    category: 'situational',
    isYakuman: false,
    description: '第一ツモで立直を宣言する',
  },
  chiitoitsu: {
    name: 'chiitoitsu',
    displayName: '七対子',
    han: 2,
    openHan: null,
    category: 'hand',
    isYakuman: false,
    description: '7種類の対子で和了する',
  },
  chanta: {
    name: 'chanta',
    displayName: '混全帯么九',
    han: 2,
    openHan: 1,
    category: 'terminal',
    isYakuman: false,
    description: 'すべての面子・雀頭に么九牌が含まれる',
  },
  ikkitsuukan: {
    name: 'ikkitsuukan',
    displayName: '一気通貫',
    han: 2,
    openHan: 1,
    category: 'hand',
    isYakuman: false,
    description: '同じ色で123・456・789の順子',
  },
  'sanshoku-doujun': {
    name: 'sanshoku-doujun',
    displayName: '三色同順',
    han: 2,
    openHan: 1,
    category: 'hand',
    isYakuman: false,
    description: '3色で同じ数字の順子',
  },
  'sanshoku-doukou': {
    name: 'sanshoku-doukou',
    displayName: '三色同刻',
    han: 2,
    openHan: 2,
    category: 'hand',
    isYakuman: false,
    description: '3色で同じ数字の刻子',
  },
  sankantsu: {
    name: 'sankantsu',
    displayName: '三槓子',
    han: 2,
    openHan: 2,
    category: 'hand',
    isYakuman: false,
    description: '3つの槓子',
  },
  toitoi: {
    name: 'toitoi',
    displayName: '対々和',
    han: 2,
    openHan: 2,
    category: 'hand',
    isYakuman: false,
    description: '4つの刻子（または槓子）',
  },
  sanankou: {
    name: 'sanankou',
    displayName: '三暗刻',
    han: 2,
    openHan: 2,
    category: 'hand',
    isYakuman: false,
    description: '3つの暗刻',
  },
  shousangen: {
    name: 'shousangen',
    displayName: '小三元',
    han: 2,
    openHan: 2,
    category: 'hand',
    isYakuman: false,
    description: '三元牌の刻子が2組と雀頭が1組',
  },
  honroutou: {
    name: 'honroutou',
    displayName: '混老頭',
    han: 2,
    openHan: 2,
    category: 'terminal',
    isYakuman: false,
    description: '老頭牌と字牌のみで和了する',
  },

  // 3翻役
  ryanpeikou: {
    name: 'ryanpeikou',
    displayName: '二盃口',
    han: 3,
    openHan: null,
    category: 'hand',
    isYakuman: false,
    description: '一盃口が2組ある',
  },
  junchan: {
    name: 'junchan',
    displayName: '純全帯么九',
    han: 3,
    openHan: 2,
    category: 'terminal',
    isYakuman: false,
    description: 'すべての面子・雀頭に老頭牌が含まれる',
  },

  // 6翻役
  honitsu: {
    name: 'honitsu',
    displayName: '混一色',
    han: 3,
    openHan: 2,
    category: 'color',
    isYakuman: false,
    description: '1種類の数牌と字牌のみで和了する',
  },
  chinitsu: {
    name: 'chinitsu',
    displayName: '清一色',
    han: 6,
    openHan: 5,
    category: 'color',
    isYakuman: false,
    description: '1種類の数牌のみで和了する',
  },

  // 役満
  kokushi: {
    name: 'kokushi',
    displayName: '国士無双',
    han: 13,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '13種類の么九牌を1枚ずつと、いずれか1種の対子',
  },
  'kokushi-13': {
    name: 'kokushi-13',
    displayName: '国士無双十三面待ち',
    han: 26,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '国士無双の13面待ち（ダブル役満）',
  },
  suuankou: {
    name: 'suuankou',
    displayName: '四暗刻',
    han: 13,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '4つの暗刻',
  },
  'suuankou-tanki': {
    name: 'suuankou-tanki',
    displayName: '四暗刻単騎',
    han: 26,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '四暗刻の単騎待ち（ダブル役満）',
  },
  daisangen: {
    name: 'daisangen',
    displayName: '大三元',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '三元牌の刻子が3組',
  },
  shousuushii: {
    name: 'shousuushii',
    displayName: '小四喜',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '風牌の刻子が3組と雀頭が1組',
  },
  daisuushii: {
    name: 'daisuushii',
    displayName: '大四喜',
    han: 26,
    openHan: 26,
    category: 'yakuman',
    isYakuman: true,
    description: '風牌の刻子が4組（ダブル役満）',
  },
  tsuuiisou: {
    name: 'tsuuiisou',
    displayName: '字一色',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '字牌のみで和了する',
  },
  chinroutou: {
    name: 'chinroutou',
    displayName: '清老頭',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '老頭牌のみで和了する',
  },
  ryuuiisou: {
    name: 'ryuuiisou',
    displayName: '緑一色',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '緑色の牌のみで和了する（23468索、發）',
  },
  chuuren: {
    name: 'chuuren',
    displayName: '九蓮宝燈',
    han: 13,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '門前で1112345678999+任意の1牌',
  },
  'chuuren-9': {
    name: 'chuuren-9',
    displayName: '純正九蓮宝燈',
    han: 26,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '九蓮宝燈の9面待ち（ダブル役満）',
  },
  suukantsu: {
    name: 'suukantsu',
    displayName: '四槓子',
    han: 13,
    openHan: 13,
    category: 'yakuman',
    isYakuman: true,
    description: '4つの槓子',
  },
  tenhou: {
    name: 'tenhou',
    displayName: '天和',
    han: 13,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '親の配牌時に和了している',
  },
  chiihou: {
    name: 'chiihou',
    displayName: '地和',
    han: 13,
    openHan: null,
    category: 'yakuman',
    isYakuman: true,
    description: '子の第一ツモで和了する',
  },
}
